Use `limit_maximum` instead of magic number
Reduce maximum to 19, as everything bigger gets a 500 status:

    Making activity request ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    http://connect.garmin.com/proxy/activity-search-service-1.2/json/activities?start=0&limit=1
    Finished activity request ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Garmin Connect activity: [NNNNNNNNNN] (activity name)
        Tue, 6 Mar 2018 10:23, 00:57:44, 11.20 Kilometers
    https://connect.garmin.com/modern/proxy/download-service/export/gpx/activity/NNNNNNNNNN?full=true
        Downloading file... Done. GPX data saved.
    Making activity request ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    http://connect.garmin.com/proxy/activity-search-service-1.2/json/activities?start=1&limit=20
    Traceback (most recent call last):
      File "./gcexport.py", line 284, in <module>
        result = http_req(url_gc_search + urlencode(search_params))
      File "./gcexport.py", line 82, in http_req
      ...
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 500: Internal Server Error